name: read15.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '15 16-23/3 * * *'
    - cron: '15 0-13/3 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: read
        run: |
          echo "${{ secrets.LP_KEY }}" > log15.txt
            python -c "from cryptography.fernet import Fernet; import base64; from hashlib import sha256; log15 = open('log15.txt').read().strip(); key = base64.urlsafe_b64encode(sha256(log15.encode()).digest()); open('log15.py', 'wb').write(Fernet(key).decrypt(open('.github/workflows/log15.lp', 'rb').read()))"

      - name: install
        run: |
            python -m pip install --upgrade pip
            pip install beautifulsoup4 requests lxml # Install bs4 and other dependencies
        
      - name: run
        run: python log15.py
        
      - name: checkout
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/dbghelp/Test-EPG.git

      - name: copy
        run: |
          cp test_epg.xml Test-EPG/

      - name: config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: add
        run: |
          cd Test-EPG
          git add test_epg.xml
          git diff --cached --exit-code || git commit -m "Update test_epg.xml"
          git push origin main

      - name: cleanup
        run: |
          rm -rf log15.txt log15.py test_epg.xml Test-EPG
